env:
  commonjs: true
  es6: true
  node: true
extends: airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules: {
  "camelcase": 0,
  "class-methods-use-this": 0,
  "func-names": 0,
  "implicit-arrow-linebreak": 0,
  "import/first": 0,
  "import/no-useless-path-segments": 0,
  "import/prefer-default-export": 0,
  "jsx-a11y/anchor-is-valid": 0,
  "jsx-a11y/click-events-have-key-events": 0,
  "jsx-a11y/no-static-element-interactions": 0,
  "linebreak-style": 0,
  "lines-between-class-members": 0,
  "max-len": [ 2, { "code": 120 } ],
  "no-console": 0,
  "no-else-return": 0,
  "no-lonely-if": 0,
  "no-param-reassign": 0,
  "no-plusplus": 0,
  "no-prototype-builtins": 0,
  "no-restricted-syntax": 0,
  "no-shadow": 0,
  "no-underscore-dangle": 0,
  "object-curly-newline": 0,
  "operator-linebreak": 0,
  "padded-blocks": 0,
  "prefer-destructuring": 0,
  "react/default-props-match-prop-types": 0,
  "react/destructuring-assignment": 0,
  "react/forbid-prop-types": 0,
  "react/jsx-one-expression-per-line": 0,
  "react/jsx-wrap-multilines": 0,
  "react/no-multi-comp": 0,
  "react/no-this-in-sfc": 0,
  "react/prefer-stateless-function": 0,
  "react/prop-types": 0,
  "react/require-default-props": 0,
  "react/sort-comp": 0
}
